# Generated by Django 5.1 on 2024-09-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(blank=True, db_index=True, through='base.SoldProduct', to='base.product'),
        ),
    ]
